agenda = []
agenda.append("Jose Vicente")
print(agenda)
agenda.append("Juan")
print(agenda)
agenda.append("Jorge")
print(agenda)
agenda.pop()
print(agenda)
agenda.remove("Jose Vicente")
print(agenda)
agenda.append("Jose Vicente")
agenda.append("Jorge")
print(agenda)
print(agenda[0])
